[package]
name = "fast_clip"
version = "1.0.0"
edition = "2024"

[workspace]
members = [
    "crates/reqwest_client",
    "crates/app_assets",
]

[workspace.lints]

[workspace.package]
edition = "2024"

[workspace.dependencies]
anyhow = "1.0.104"
gpui = { git = "https://github.com/zed-industries/zed" }
gpui_platform = { git = "https://github.com/zed-industries/zed", features = ["font-kit"] }
log = "0.4"
reqwest = { version = "0.12.28", features = ["json", "blocking", "rustls-tls", "stream", "rustls-tls-native-roots"] }
serde = "1.0.229"
serde_json = "1.0.151"
futures = "0.3"

[features]
default = []
static-ffmpeg = ["ffmpeg-next/static"]

[dependencies]
anyhow.workspace = true
gpui.workspace = true
gpui_platform.workspace = true
gpui-component = { git = "https://github.com/longbridge/gpui-component.git" }
gpui-component-assets = { git = "https://github.com/longbridge/gpui-component.git" }
reqwest.workspace = true
futures.workspace = true

reqwest_client = { path = "crates/reqwest_client" }
app_assets = { path = "crates/app_assets" }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
smallvec = "1.15.2"
image = "0.25.10"
ffmpeg-next = { version = "8.1.0", default-features = false, features = ["codec", "format", "software-resampling", "software-scaling"] }
async-channel = "2.5.0"
ringbuf = "0.4.8"
cpal = "0.17.3"
rust-i18n = "3.1.5"
path-absolutize = "3.1.1"
atomic_float = "1.1.0"
semver = "1.0.28"
strum = "0.28.0"
strum_macros = "0.28.0"

[build-dependencies]
winres = "0.1.12"

[profile.release-static]
inherits = "release"
codegen-units = 1
lto = "thin"
strip = "symbols"

[package.metadata.bundle]
name = "FastClip"
identifier = "com.him049.fastclip"
icon = ["assets/AppIcon.icns"]
category = "Utility"
short_description = "A fast video clipping tool."
